### ISSUE TITLE
An example with data

### ISSUE THREAD

**Issue by RuthAngus** [gomesdasilva/ACTIN#1]
Hi João, 

Nice package! Would it be possible for you to include a HARPS spectrum and a worked example here with the code?

Thank you!

**Comment by gomesdasilva** [comment]
Updated the code to include test spectra in folder test_files
To test the code you can run with minimum arguments:
$ python actin.py -f test_files/*e2ds*.fits -i I_CaII

"-f" to chose the file(s); "-i" to chose which index or indices to calculate (from the  config file list)

use "-h" for help.

The readme.md file includes an example in the end

**Comment by RuthAngus** [comment]
Thank you for including this example! Could you update the README so that users can copy and paste the example given there into their command line and have the code run on this example?

**Comment by gomesdasilva** [comment]
Added example to README

**Comment by RuthAngus** [comment]
Hi, 

I still can't get the example to work, am I doing something wrong? I install the package
(_pip install actin_) then I type _actin -cfg True_. I'd like to run the example but if I just type _actin -f test_files/*e2ds.fits -i I_CaII_, I'm not pointing at the right file and the example doesn't run. Is there something else I need to do?

**Comment by gomesdasilva** [comment]
are you inside the actin directory which have the test_files directory inside it?

**Comment by RuthAngus** [comment]
No I'm not, and if a user installs this package with pip, they may not necessarily be in the right directory. I think a user should be able to run an example by copying and pasting a list of commands. So if this example requires you to be in the right directory, could you provide the commands to cd into that directory? If this is tricky (the directory depends on the OS), perhaps you could explicitly state that in order to run the examples you give it might be easier to install from Github? Then you always know where the directory is.

**Comment by gomesdasilva** [comment]
Ah, ok, I understand what you mean. I will automate the process of choosing the correct test directory.

**Comment by RuthAngus** [comment]
Great, thank you!

**Comment by gomesdasilva** [comment]
Just updated PyPI with version 1.2.2.
The tests chose the files automaticaly, by using actin -t "option"
where "option" can be "e2ds", "s1d" or "adp" to test the different kind of files

**Comment by gomesdasilva** [comment]
also added description for the "-t" option in the README file

**Comment by RuthAngus** [comment]
Thanks! Somewhere in the "Testing code with minimum arguments" section, would you mind also providing the path to the directory the user will need to cd to in order to run the test if they install with pip?

**Comment by gomesdasilva** [comment]
it should work if you write "actin -t e2ds" from any directory, can you confirm?

**Comment by RuthAngus** [comment]
Oh sorry, my bad! Yes, that works! Could you add that note to the README? I know you added a description of the -t option, but, as clearly demonstrated by me,  it helps to spell it out!

**Comment by gomesdasilva** [comment]
done
