### ISSUE TITLE
No references?

### ISSUE THREAD

**Issue by RuthAngus** [gomesdasilva/ACTIN#2]
Hi João, It looks like your references don't show up in the paper. Do you know what might be producing this error?

**Comment by gomesdasilva** [comment]
Hi Ruth, it is an issue with Github markdown language. It should work if you use another markdown language to compile paper.md. For example, in the JOSS paper example "Gala" (https://github.com/adrn/gala/blob/master/paper/paper.md) the references file (.bib) is there but Github does not show the references
