### ISSUE TITLE
Error when running ACTIN

### ISSUE THREAD

**Issue by RuthAngus** [gomesdasilva/ACTIN#5]
Hi, 

Even though everything seemed to work yesterday, I now get a different output. Do you know what might be happening?

Now when I run 'actin -f e2ds'

I get the following output:

actin 1.2.2

#----------------#
# STARTING ACTIN #
#----------------#

--------------------
EXECUTING ACTIN_FILE
--------------------
*** ERROR: actin: Cannot recognise file type

---------------------------
Weight used in flux:	None
Normalization of flux:	npixels
Files analysed:		1
Save output:		False
Elapsed time:		0.0000 min

**Comment by gomesdasilva** [comment]
Hi,
to test use "actin -t option" where option can be "e2ds", "s1d" or "adp"

The "-f" is used when you specify the full file name and path

**Comment by RuthAngus** [comment]
Oh I'm so sorry, I must have just mistyped an "f" instead of a "t"! I'm so sorry about that.

**Comment by gomesdasilva** [comment]
No it was my mistake, I mistyped “f” in the readme file :)
