### ISSUE TITLE
Test fails with fresh install

### ISSUE THREAD

**Issue by j-faria** [gomesdasilva/ACTIN#9]
Running `actin -t e2ds` fails with the following error

```
LOADING DATA FROM CONFIG FILE
-----------------------------
*** ERROR: Index I_Ha06 is not in the config file.
```

**Comment by gomesdasilva** [comment]
The code is using a config file without that index, are you using the standard config file (i.e. not using as an input option)?

It could be an old version of the config file was installed but the new version of actin did not actualise it. Is the rest of the code running well if you try to calculate I_Ha06?

**Comment by j-faria** [comment]
It was an old `config_lines.txt` file. 
I would suggest to replace the file on install, but I'm not sure if that's always what you want. 

Closing this for now.
